name: Clojure CI

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps ; pip3 install -r requirements.txt
    - name: Run checks on person app
      run: lein run check test/system/person/person.app.edn
    - name: Run checks on todo app
      run: lein run check test/system/todo/todo.app.edn
    - name: Run system tests on person app
      run: source test/system/test.sh
